# questions.py

ai_questions = [
    {"question": "Which of the following is not a type of AI?",
     "options": ["Narrow AI", "General AI", "Super AI", "Fast AI"],
     "answer": "Fast AI"},
    {"question": "Who is considered the father of AI?",
     "options": ["Alan Turing", "John McCarthy", "Geoffrey Hinton", "Andrew Ng"],
     "answer": "John McCarthy"},
    {"question": "Which AI technique mimics the human brain?",
     "options": ["Genetic Algorithms", "Fuzzy Logic", "Neural Networks", "Rule-Based Systems"],
     "answer": "Neural Networks"},
    {"question": "What is the Turing Test used for?",
     "options": ["To test computer speed", "To test human intelligence", "To test AI behavior", "To test algorithm efficiency"],
     "answer": "To test AI behavior"},
    {"question": "What does NLP stand for in AI?",
     "options": ["Neural Language Processing", "Natural Logic Parsing", "Natural Language Processing", "None of the above"],
     "answer": "Natural Language Processing"},
    {"question": "Which of the following is a popular AI library in Python?",
     "options": ["NumPy", "OpenCV", "TensorFlow", "Matplotlib"],
     "answer": "TensorFlow"},
    {"question": "What is reinforcement learning?",
     "options": ["Learning from labeled data", "Learning from rewards", "Learning from examples", "Learning from humans"],
     "answer": "Learning from rewards"},
    {"question": "Which search technique is used in games like chess?",
     "options": ["Linear Search", "Binary Search", "Minimax", "DFS"],
     "answer": "Minimax"},
    {"question": "Which of the following is a type of supervised learning?",
     "options": ["Clustering", "Classification", "Association", "Anomaly detection"],
     "answer": "Classification"},
    {"question": "Which AI concept helps in reasoning under uncertainty?",
     "options": ["Deterministic models", "Fuzzy logic", "Graphs", "Sorting algorithms"],
     "answer": "Fuzzy logic"},
]

ml_questions = [
    {"question": "Which of the following is a supervised learning algorithm?",
     "options": ["K-Means", "Linear Regression", "PCA", "Apriori"],
     "answer": "Linear Regression"},
    {"question": "What is overfitting in ML?",
     "options": ["Model performs poorly on training data", "Model performs well on all data", "Model performs well on training but poorly on test data", "Model fails to run"],
     "answer": "Model performs well on training but poorly on test data"},
    {"question": "Which technique is used to reduce dimensionality?",
     "options": ["KNN", "SVM", "PCA", "RNN"],
     "answer": "PCA"},
    {"question": "Which of these is NOT a performance metric for classification?",
     "options": ["Accuracy", "Precision", "Recall", "MSE"],
     "answer": "MSE"},
    {"question": "Which ML algorithm is inspired by the human brain?",
     "options": ["KNN", "Naive Bayes", "Neural Networks", "SVM"],
     "answer": "Neural Networks"},
    {"question": "Which is used for clustering?",
     "options": ["K-Means", "Decision Trees", "Random Forest", "Logistic Regression"],
     "answer": "K-Means"},
    {"question": "Which of the following is a type of regression?",
     "options": ["Linear Regression", "KNN", "Decision Trees", "RNN"],
     "answer": "Linear Regression"},
    {"question": "What does 'bias' refer to in ML models?",
     "options": ["Randomness", "Assumptions made by the model", "Model error", "Accuracy"],
     "answer": "Assumptions made by the model"},
    {"question": "Which library is best suited for ML in Python?",
     "options": ["scikit-learn", "BeautifulSoup", "Flask", "Matplotlib"],
     "answer": "scikit-learn"},
    {"question": "Which algorithm is used in spam detection?",
     "options": ["Linear Regression", "Naive Bayes", "PCA", "K-Means"],
     "answer": "Naive Bayes"},
]

genai_questions = [
    {"question": "What is the core concept behind Generative AI?",
     "options": ["Classification", "Prediction", "Creation", "Translation"],
     "answer": "Creation"},
    {"question": "Which model type is commonly used for text generation?",
     "options": ["CNN", "LSTM", "GAN", "Transformer"],
     "answer": "Transformer"},
    {"question": "What does GPT stand for?",
     "options": ["General Preprocessing Transformer", "Generative Pretrained Transformer", "Generative Parsing Transformer", "Graph Pretrained Transformer"],
     "answer": "Generative Pretrained Transformer"},
    {"question": "Which of the following is a GAN used for?",
     "options": ["Summarization", "Classification", "Image Generation", "Translation"],
     "answer": "Image Generation"},
    {"question": "Which company created the GPT models?",
     "options": ["Google", "Meta", "OpenAI", "Amazon"],
     "answer": "OpenAI"},
    {"question": "What is diffusion model used for?",
     "options": ["Audio analysis", "Text summarization", "Image generation", "Speech-to-text"],
     "answer": "Image generation"},
    {"question": "Which is a risk of Generative AI?",
     "options": ["Improved data", "Bias amplification", "Speed", "Less cost"],
     "answer": "Bias amplification"},
    {"question": "Which API provides access to Granite models?",
     "options": ["OpenAI", "IBM Watsonx", "Anthropic", "Cohere"],
     "answer": "IBM Watsonx"},
    {"question": "Which tool is used to build GenAI web interfaces?",
     "options": ["Gradio", "Selenium", "Flask", "TensorBoard"],
     "answer": "Gradio"},
    {"question": "Which task is NOT suitable for GenAI?",
     "options": ["Code generation", "Painting images", "Sorting algorithms", "Text generation"],
     "answer": "Sorting algorithms"},
]

math_questions = [
    {"question": "What is the derivative of x²?",
     "options": ["x", "2x", "x²", "2"],
     "answer": "2x"},
    {"question": "What is the value of π (approx)?",
     "options": ["2.14", "3.14", "1.41", "4.13"],
     "answer": "3.14"},
    {"question": "What is the integral of 1/x?",
     "options": ["log(x)", "x", "1/x²", "x²/2"],
     "answer": "log(x)"},
    {"question": "What is 7! (factorial)?",
     "options": ["5040", "720", "120", "40320"],
     "answer": "5040"},
    {"question": "Solve: 3x + 2 = 11",
     "options": ["x=2", "x=3", "x=4", "x=5"],
     "answer": "x=3"},
    {"question": "Which number is a prime?",
     "options": ["4", "6", "9", "7"],
     "answer": "7"},
    {"question": "What is the area of a circle with radius 3?",
     "options": ["6π", "9π", "3π", "12π"],
     "answer": "9π"},
    {"question": "What is the square root of 81?",
     "options": ["7", "8", "9", "10"],
     "answer": "9"},
    {"question": "What is the sum of angles in a triangle?",
     "options": ["90°", "180°", "360°", "270°"],
     "answer": "180°"},
    {"question": "What is the value of log(100) base 10?",
     "options": ["1", "2", "10", "100"],
     "answer": "2"},
]
